
name: AI1

on:

  push:
    branches: [ "AI1" ]
  pull_request:
    branches: [ "AI1" ]


  workflow_dispatch:
    inputs:
      log_errors:
        description: 'Logs (true/false)'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'

jobs:

    test:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v4

        - name: Setup 
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"

        - name: Install 
          run: |
            pip install -r requirements.txt
            pip install pytest

        - name: Run test_not_null.py
          id: test_not_null
          continue-on-error: true
          run: python -m pytest tests/test_not_null.py -v

        - name: Run test_pandas.py
          id: test_pandas
          continue-on-error: true
          run: python -m pytest tests/test_pandas.py -v

        - name: logs 
          if: ${{ github.event.inputs.log_errors == 'true' && (steps.test_not_null.outcome == 'failure' || steps.test_pandas.outcome == 'failure') }}
          run: |
            mkdir -p logs
            echo "Tests failed!" >> logs/test-errors.log


        - name: logs file
          if: ${{ github.event.inputs.log_errors == 'true' && (steps.test_not_null.outcome == 'failure' || steps.test_pandas.outcome == 'failure') }}
          uses: actions/upload-artifact@v4
          with: 
            name: test-error-logs-${{ github.run_number }}
            path: logs/test-errors.log
        
        - name: Fail if tests failed
          if: steps.test_not_null.outcome == 'failure' || steps.test_pandas.outcome == 'failure'
          run: exit 1


    build:
      
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v4

        - name: login to dockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: build and push docker image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest

        
    deploy:
      
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v4

        - name: login to Azure
          uses: azure/login@v1
          with: 
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ secrets.AZURE_APP_NAME }}
            images: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest




